name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          chmod +x ./mods.sh
          ./mods.sh build

      - name: Upload release assets (for tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}